version: '3.4'

services:
  productdb:
    image: postgres

  petdb:
    image: postgres

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

  petapi:
    image: ${DOCKER_REGISTRY-}petapi
    build:
      context: .
      dockerfile: PetApi/Dockerfile

volumes: 
  postgres_product:
  postgres_pet:


