version: '3.4'

services:
  productdb:
    image: postgres

  petdb:
    image: postgres

  cartdb:
    image: postgres

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

  petapi:
    image: ${DOCKER_REGISTRY-}petapi
    build:
      context: .
      dockerfile: PetApi/Dockerfile

  cartapi:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: ..
      dockerfile: PetLoverApp/Services/CartApi/Dockerfile

volumes: 
  postgres_product:
  postgres_pet:
  postgres_cart:



