version: '3.4'

services:
  productdb:
    image: postgres

  petdb:
    image: postgres

  cartdb:
    image: postgres

  distributedcache:
    image: redis

  customerdb:
    image: postgres

  bookingdb:
    image: postgres

  messagebroker:
    image: rabbitmq:management

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/ProductApi/Dockerfile

  petapi:
    image: ${DOCKER_REGISTRY-}petapi
    build:
      context: .
      dockerfile: Services/PetApi/Dockerfile

  cartapi:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/CartApi/Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Services/CustomerApi/Dockerfile

  bookingapi:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Services/BookingApi/BookingApi/Dockerfile

volumes: 
  postgres_product:
  postgres_pet:
  postgres_cart:
  postgres_customer:
  postgres_booking:





