<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ffd80d72-cf2e-46ba-8cb9-2274fdc10abe</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
	<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
	<PackageReference Include="Carter" Version="8.2.0" />
	<PackageReference Include="Marten" Version="7.37.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\Common.Lib\Common.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Dto\" />
    <Folder Include="Customers\GetCustomerById\Endpoint\" />
    <Folder Include="Customers\GetCustomerById\RequestHandling\" />
    <Folder Include="Customers\DeleteCustomer\Endpoint\" />
    <Folder Include="Customers\DeleteCustomer\RequestHandling\" />
    <Folder Include="Customers\UpdateCustomer\Endpoint\" />
    <Folder Include="Customers\UpdateCustomer\RequestHandling\" />
    <Folder Include="Customers\CreeateCustomer\Endpoint\" />
    <Folder Include="Customers\CreeateCustomer\RequestHandling\" />
  </ItemGroup>

</Project>
