<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6accc2fc-f5ac-4de4-ab41-2e8823cde533</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reservation.Application\Reservation.Application.csproj" />
    <ProjectReference Include="..\Reservation.Infrastructure\Reservation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
